class Meal {
  String image;
  String name;
  int min;
  double price;
  List<String> ingredients;
  List<String> steps;

  Meal(
      {
        required this.name,
        required this.image,
      required this.min,
      required this.price,
      required this.ingredients,
      required this.steps});
}
final meals = [
  [
    Meal(name: "Avocado-Egg Toast", image: 'https://www.eatingwell.com/thmb/ojgAlF_x0-s9wneV89lgoHrOfLU=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/44735191-6e31f871f8324df2b214745a7d09b499.jpg', min: 5, price: 10, ingredients: ["1.Avakado, 2.choy qoshiq maydalangan qalampir, 3.choy qoshiq sarimsoq kukuni, 4. 1bo'lak bug'doy non, 5.1katta tuxum, qovurilgan. 6.1 choy qoshiq Siriracha(ixtiyoriy), 7.osh qoshiq piyoz, dilimlenmis(ihtiyoriy) "], steps: ["Bir marta sinab ko'ring va biz rozi bo'lasiz deb o'ylaymiz: avakado tostini tuxum bilan to'ldirish - bu ajoyib nonushta."]),
    Meal(name: "Charred Shrimp, Pesto & Quinoa Bowls", image: 'https://www.eatingwell.com/thmb/kmV_tZUoH1d4xNU5n3aDIeKsY50=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/6707072-9c95fd6020c0463c86ba79e4baf20548.jpg', min: 25, price: 8, ingredients: ["1. 1 stakan tayyorlangan pesto, 2. 2 osh qoshiq balsamik sikra, 3. 1 osh qoshiq zaytun moyi, 4. choy qoshiq tuz, 5. choy  qoshiq maydalangan qalampir, 6. 1 funt tozalangan va maydalangan katta qisqichbaqalar(16-20dona), qurutilgan, 7. 4 stakan arugula, 8. 2 stakan pishirilgan quinoa, 9. 1 stakan yarimiga bo'lingan olcha pomidorlari, 10. 1ta avakado, tug'ralgan "], steps: ["Bu qisqichbaqalar, pesto va kinoa idishlari mazali, sog'lom, chiroyli va tayyorlash uchun 30 daqiqadan kamroq vaqt ketadi. Boshqacha qilib aytadigan bo'lsak, ular asosan haftalik tungi kechki ovqatdir. Qo'shimcha sabzavotlar qo'shing va qisqichbaqalarni tovuq, biftek, tofu yoki edamame bilan almashtiring."]),
    Meal(name: "Skillet Lemon Chicken & Potatoes with Kale", image: 'https://www.eatingwell.com/thmb/5K2lylMdWvf2lg1apB6_W6cs7Ho=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/64878671-d4a6402e17d548ddbc66e1d20f8c58b8.jpg', min: 50, price: 0, ingredients: ["1. 3 osh qoshiq  zaytun moyi, bo'lingan, 2. 1kg suyaksiz, tersiz tovuq sonlari kesilgan 3. choy   qoshiq tuz, bo'lingan, 4.choy qoshiq maydalangan qalampir, bo'lingan, 5. 1funt chaqaloq Yukon Gold kartoshkasi, uzunligi bo'ylab yarmiga bo'lingan, 6. chashka past natriyli tovuq suvi 7. 1t katta limon, va urug'larni olib tashlang. 8.chinngullar sarimsoq, maydalangan. 8. 1 osh qoshiq tug'ralgan yangi tarragon. 6 stakan chaqaloq karam"], steps: ["Bu oson bir tovada qovurilgan limonli tovuq haftalik kechki ovqat uchun juda mos keladi. Suvli tovuq sonlari chaqaloq kartoshkasi va karam bilan bir xil skovorodkada pishiriladi, qoniqarli taom uchun qo'shimcha minimal tozalash qo'shiladi.Kartoshkani pishiringKeyin kartoshka qo'shiladi va qizarguncha kesilgan tomoni pastga qarab pishiriladi. Biz chaqaloq Yukon Gold kartoshkasidan foydalanamiz, ular uzunligi bo'ylab yarmiga bo'linadi, shuning uchun ular bir tekis va retseptda ajratilgan vaqtda pishiriladi. Past natriyli tovuq suvi, limon bo'laklari, sarimsoq va yangi tarragon kartoshka bilan aralashtiriladi. Agar siz yangi estragon topa olmasangiz, yangi oregano, marjoram yoki chervil bilan almashtiring."]),
    Meal(name: "Tuna, White Bean & Dill Salad", image: 'https://www.eatingwell.com/thmb/m7Vk0usWacISXudNxx6HtNziGr4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/5940766-0b3bce5e41694d6f95caf70ee1b0dfdc.jpg', min: 30, price: 0, ingredients: ["1. 1(untsiya) tuz qo'shilgan canneline loviya(oq loviya), yuviladi va quritiladi. 2. (5 unitsa) quti qattiq oq orkinos(suv to'plami), quritilgan va bo'laklatga bo'lingan. 3. chashka tug'ralgan qizil  piyoz. 4. 3 osh qoshiq 1 choy qoshiq asal Dijon uslubidagi xantal, bo'lingan. 5. 2 osh qoshiq yengil mayanez. 6. 2 osh qoshiq sirka sirkasi, bo'lingan 7. 1 chcoy qoshiq qurutilgan arpadobiyon, bo'lingan 8. 2 osh qoshiq zaytun moyi. 9. choy qoshiq kosher tuzi. 10. 6stakan yangi chaqaloq ismaloq. 11. 2stakan kubikli, pishirilgan va sovutilgan lavlagi. 12. 1 novda Tug'ralgan yangi arpadodiyon va/yoki maydalangan qalampir" ], steps: ["Konservalangan orkinosni yangi cho'qqilarga ko'taring: qaymoqli kanellini loviya, yangi arpabodiyon va achchiq Dijon sosu. STEP 1:Katta idishda loviya, orkinos va piyozni birlashtiring. Kiyinish uchun 3 osh qoshiq xantal, mayonez, 1 osh qoshiq sirka, 1 choy qoshiq quritilgan arpabodiyon va limon-qalampir ziravorlarini kichik idishga soling. Tuna aralashmasiga kiyinishni qo'shing; qo'yish uchun muloyimlik bilan tashlang. Yoping va 2 dan 4 soatgacha sovutib oling. STEP 2: Vinaigrette tayyorlang: yog'ni, qolgan 1 osh qoshiq sirkani, qolgan 1 choy qoshiq xantalni, tuzni va qolgan 1/8 choy qoshiq quritilgan arpabodiyonni kichik vintli idishga soling. Yoping va yaxshilab silkiting. Katta idishda ismaloq va lavlagi birlashtiring. Xizmat qilishdan oldin, ismaloq aralashmasi ustiga vinaigrette quying; qo'yish uchun muloyimlik bilan tashlang. STEP 3:Xizmat qilish uchun, ismaloq aralashmasi bilan to'rtta xizmat plastinasini yoping. Orkinos aralashmasi bilan tepaga. Agar so'ralsa, yangi arpabodiyon va / yoki qalampir seping "]),
    Meal(name: "Curried Sweet Potato & Peanut Soup", image: 'https://www.eatingwell.com/thmb/rtLnOzhy4cMCRsXaBh5Ptw8cc5o=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/6349105-212e7c638f4c43e8a36ac6be05b03140.jpg', min: 30, price: 25, ingredients: ["1. 2 osh qoshiq kalona yog'i, 2. 1 stakan tug'ralgan sariq piyoz, 3. 1osh qoshiq maydalangan sarimsoq, 4. 1 osh qoshiq maydalangan yangi zanjabil, 5. 4 choy qoshiq qizil ko'ri pastasi, 6. 1 serrano chili, qovurg'a va urug'lar olib tashlangan, maydalangan. 7. 1 funt shirin kartoshka, tozalangan va kub shaklida (1/2 dyuymli bo'laklar) 8. 1 stakan suv, 9. 1 stakan'lite' kakos suti. 10. stakan tuziz quruq qovurilgan yeryong'oq."], steps: ["Ushbu mazali sho'rva retseptida shirin kartoshka tez hindiston yong'og'i koriida qaynatiladi, natijada sarimsoq va zanjabil notalari bilan tiniqlangan qaymoqli, qalin bulon paydo bo'ladi. Biz yeryong'oqni arzon narxi va ko'p qirrali ta'mi uchun yaxshi ko'ramiz. Ular shuningdek, oqsilning ajoyib manbaidir - 1 untsiyada 7 gramm mavjud."]),
  ],
  [
    Meal(name: "To'g'ri ovqatlanish- uzoq umr garovi", image: 'https://olamsport.com/upload/storage/114763_680.jpg', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Kishi keksaygani sayin hazm a’zolarining taomlarni qayta ishlash (gidrolizlash yoki fermentlar yordamida parchalash) hamda so‘rish qobiliyati pasayib boradi. Organizmning oqsillarga bo‘lgan ehtiyojini qondirishda qiyin hazm bo‘ladigan go‘sht va go‘sht mahsulotlari, no‘xat, loviya, mosh o‘rniga baliq va sut, qatiq, smetana, pishloq kabi bir muncha oson hazm bo‘ladigan mahsulotlarni iste’mol qilgan ma’qul. Boz ustiga baliq va sut mahsulotlaridagi yog‘ ham unchalik xavfli emas."]),
    Meal(name: "Kunlik ta'omlar", image: 'https://shifo.uz/upload/iblock/b99/b99e517050f289fa29009d9549bfff46.jpg', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Organizmning barcha oziq moddalarga bo‘lgan talabini qondirish uchun kundalik taomlarning xilma-xil bo‘lishi muhim ahamiyatga ega. Masalan doim bir xil non yeyishdan ko‘ra arpa, makkajo‘xori, tariq, so‘li qo‘shib tegirmondan o‘tkazilgan undan tayyorlangan non iste’mol qilish organizm uchun makro- va mikro elementlar bilan ta’minlanishda ancha foydali. Xuddi shuningdek turli-tuman ko‘katlardan, sabzavot va poliz mahsulotlaridan salatlar tayyorlab iste’mol qilishda ularning bargi va poyasidan ham foydalanish (masalan, sabzi, lavlagi va boshqalar) ahamiyatli. Lavlagi barglarida inson uchun kerakli madanli moddalar, vitaminlar uning poyasiga nisbatan ko‘p bo‘ladi."]),
    Meal(name: "Uzoq umr garovi", image: 'https://www.uza.uz/upload/medialibrary/592/mantelzorg_hulp_wat_is_pic905_905x505_28462.jpg', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Har bir keksa va qariya sihat-salomatligi, uzoq umr ko‘rishini ta’minlashi uchun yoshlik davrida taomlanishga nisbatan bo‘lgan ayrim odat va o‘rganishlaridan (shosha-pisha, vaqti-bevaqt to‘g‘ri kelgan taomlarni oz-ko‘p iste’mol qilish va boshqalar) voz kechib taomlar tarkibida sut, qatiq, pishloq, baliq, go‘sht, kepagi olinmagan qora yoki jaydari non, ko‘katlar, meva-cheva, rezavor mevalar, poliz va sabzavot mahsulotlari, o‘simlik yog‘larining yetarli bo‘lishiga erishishi va bir vaqtning o‘zida tuxum, baliq ikrasi, shirinliklar, oq un qo‘shib tayyorlangan pishiriqlar, tort, achchiq choy, quyuq kofe kabi oziq moddalarni esa cheklangan miqdorda iste’mol qilishga o‘tishi kerak"]),
    Meal(name: "Tartib muhim", image: 'https://zamin.uz/uploads/posts/2019-01/1548795060_b674126e5051d971f7eeb8ae6797979f_720x480.jpg', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Pala–partish, shosha-pisha to‘g‘ri kelgan paytda taomlanaverish keksa va qariyalarda hazm a’zolari faoliyatiga salbiy ta’sir qiladi. Gap shundaki oshqozonga tushgan ovqat to‘liq ichaklarga o‘tib, yana ovqatlanish ishtiyoqi paydo bo‘lganida taomlanish kerak. Aks holda, oshqozonda ovqat borligida yoki taomlanishga ishtaha bo‘lmasi turib ovqatlanilsa hazm a’zolarining odatdagi faoliyati buziladi (hazm qiluvchi shiralar tegishli tarkib va miqdorda ajralmaydi va boshqalar)."]),
  ],
  [
    Meal(name: "Chekishni tashlash uchun xalq tabobatidan maslahatlar", image: 'https://avitsenna.uz/wp-content/uploads/2017/07/chekishni-tashlash-min.jpg', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Siz chekishni tashlamoqchisiz, ammo cira buni uddasidan chiqa olmayapsiz. Unda sizga xalq tabobati yordam berishi mumkin. Dunyoda har 6 soniyada bir kishi tamaki chekishdan ko‘z yumadi! Tamaki chekishni tashlashga ahd qilganingiz bilan tabriklaymiz! Bu qaror qattiq va mustahkam bo‘lishi kerak! Xalq tabobati esa bu og‘ir masalada yordam beradi."]),
    Meal(name: "Ishtahani qanday kamaytirish mumkin?", image: 'https://avitsenna.uz/wp-content/uploads/2023/06/appetit-1024x683-1.jpg', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ['Kuchli ishtahaning har doim ortiqcha vaznga olib keladi va bu semirish, diabet va yurak-qon tomir kasalliklariga sabab bo’lishi mumkin. Ishtaha qanday paydo bo’ladi va uni boshqarish mumkinmi? Ishtaxa markazi gipotalamusda joylashgan. Ishtahani keltirib chiqaradigan eng keng tarqalgan sabab bu qondagi qand miqdorini keskin o’zgarishi. Qonda glyukoza miqdori pasayganda, gipotalamus signal yuboradi, natijada ochlik hissi paydo bo’ladi. Glyukoza darajasi normallashganda to’yish hissi paydo bo’ladi.']),
    Meal(name: "E vitamini haqida", image: 'https://avitsenna.uz/wp-content/uploads/2023/06/vitamin-e-feature_8.jpg', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ['E vitamini asosiy antioksidantlardan biridir. Tananing qarishini oldini oladi, hujayralar oziqlanishini yaxshilaydi va ularning yangilanishiga olib keladi. E vitamini XIX asrning boshlarida aniqlangan. Olimlar aka-uka Shyutlar kemiruvchilarda tajriba oʻtkazganlarida, ular faqat toʻliq sut bilan oziqlangan. Kalamushlar normal rivojlandi, lekin koʻpaya olmadi. Shyut yetishmayotgan moddalar kemiruvchilar juda yaxshi koʻradigan koʻkatlar va bugʻdoylarda ekanligini taxmin qildi. Keyinchalik gipoteza tasdiqlandi — yetishmayotgan modda E vitamini edi']),
    Meal(name: "Bosh og'rig'ini samarali yo'l bilan qoldirish", image: 'https://i0.wp.com/rgtravnik.ru/wp-content/uploads/2016/05/%D0%BC%D1%8F%D1%82%D0%B03.jpg', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Yalpiz moyi: Agar siz lavandani yoqtirmasangiz, yalpiz samara berishi mumkin — u ham stressga barham berib, ba’zan bosh og’rig’iga javobgar nervlarni tinchlantiradi. Yalpiz moyini bosh terisiga o’n daqiqa davomida surtib, uqalash tavsiya etiladi. Yalpiz moyi bo’lmasa, yangi yalpiz barglarini qo’llashingiz mumkin: ularni yaxshilab ezib, chakka, bo’yin va peshonaga muloyimlik bilan surting"]),
  ],
  [
    Meal(name: "Deadlift", image: 'https://www.mensjournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_760/MTk2MTM2NjQ2NDAzODkyMzY5/1-deadlift.webp', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Aytish mumkinki, barcha mashqlarning qiroli, o'lik yuk har bir asosiy mushak guruhiga qattiq ta'sir qiladi va bu, ehtimol, kuchning eng katta sinovidir. Ishtirok etgan barcha mushaklar tufayli u qon oqimiga juda ko'p miqdorda testosteron (mushak hosil qiluvchi gormon) chiqaradi. Shu sababli, o'lik yuk har qanday fitnes rejasi uchun ajoyib poydevor hisoblanadi."]),
    Meal(name: "Orqaga cho'kish", image: 'https://www.mensjournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_503/MTk2MTM2NjQ2OTM1NzE3MDA5/2-back-squat.webp', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Deadlift singari, shtangani orqaga cho'zish ham tanadagi deyarli barcha asosiy mushak guruhlariga uriladi va oyoqlarni rivojlantiruvchi harakatlar qiroli hisoblanadi. Har qanday sportchi tez yugurishi, baland sakrashi va butun kuchini oshirib borishi uchun cho'zilishni ta'kidlaydi."]),
    Meal(name: "Dastgoh pressi", image: 'https://www.mensjournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_760/MTk2MTM2NjQ2NDAyMDU3MzYx/3-bench-press.webp', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Dunyodagi har bir sport zaliga tashrif buyuruvchidan Whaddya skameykasi? deb so'rashadi. kamida bir marta. Bu harakat kuchli, aniq belgilangan ko'krak, elka va tricepsni rivojlantirish uchun mas'uldir, bu esa ko'ylak bilan yoki ko'ylaksiz ko'proq buyruq beruvchi mavjudlikka olib keladi. Buni testosteronning mushak qurish ta'siri bilan birlashtiring, bu harakatni chiqaradi va sizning kichkina qora kitobingiz toldirilganligini tomosha qilish kifoya."]),
    Meal(name: " Pullup", image: 'https://www.mensjournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_760/MTk2MTM2NjQ2NjY5OTAyOTkz/7-pullup.webp', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Hech narsa to'liq men kattaman demaydi, keng elkalar to'plami kabi; keng orqa ham og'rimaydi. Yelkangizni keng ko'rsatadigan katta, fan shaklidagi mushaklarni (latissimus dorsi, aka, lats) rivojlantirish uchun eng yaxshi harakat an'anaviy tortishishdir. Bu testosteronning chiqarilishiga olib keladigan katta, ko'p qo'shma harakat, ya'ni kuch va mushaklarning umumiy rivojlanishi yaxshilanadi."]),
    Meal(name: "Tibbiyot to'pi zarbasi", image: 'https://www.mensjournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_441/MTk2MTM2NjQ2NjcxMTQ4MTc3/8-medicine-ball-slam.webp', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Ba'zi yigitlar biz jurnallarda ko'rgan fitnes modellari kabi yirtilgan o'rta qismini rivojlantirish uchun umr bo'yi ishlaydi. Boshqalar intizomli ovqatlanish sirini va qorin bo'shlig'i uchun eng yaxshi mashqlarni bilishadi, ularning hech biri siqilish yoki o'zgarish emas. Tibbiyot to'pi o'rta qismdagi daralar o'yib, qorin bo'shlig'ingizni Manxetten markazining ko'cha xaritasiga o'xshatadi va mashg'ulotingizga ko'p miqdorda kardio qo'shadi, shunda siz o'sha ko'rinishni saqlab qolasiz."]),
    Meal(name: "To'xtatilgan teskari qator", image: 'https://www.mensjournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_600/MTk2MTM2NjQ2MTM2MjQzMzQ1/13-suspended-inverted-row.webp', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Ko'pincha, tananing har ikki tomoni bilan amalga oshiriladigan harakat zaifliklar yoki nomutanosibliklarni ko'rsatmaydi. Qatorning bu o'zgarishi bundan mustasno - bu sizning kamchiliklaringizni yanada aniqroq qiladi. Ammo iyagingizni ko'taring, do'stim: to'xtatib turish murabbiyi ushbu nomutanosiblik yoki zaifliklarni tuzatishga yordam beradi, bu esa to'g'ri harakat shakllari tufayli uzoq muddatli bo'g'imlarning sog'lig'iga olib keladi."]),
  ],
  [
    Meal(name: "Yurish", image: 'https://www.eatthis.com/wp-content/uploads/sites/4/2022/10/fit-woman-walking-workout-slim-down-get-toned.jpg?resize=800,586&quality=82&strip=all', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Agar vazn yo'qotib, o'z shakliga qaytishni istasangiz, yaxshi eski uslubda piyoda uxlamang. “Jismoniy mashqlar” deb hisoblanmasa-da, kunlik yurish vazn yo‘qotish uchun qilishingiz mumkin bo‘lgan eng ta’sirli odatlardan biridir, chunki bu butun hafta davomida kaloriyalar miqdorini oshirishning kam ta’sirli usulidir”, deydi Tayler Rid, asoschisi. PTPioneer.com va so'nggi 15 yil davomida sog'liqni saqlash va fitnes olamida ishtirok etgan shaxsiy murabbiy. Har kuni kamida 30 daqiqa tez yurishni maqsad qiling"]),
    Meal(name: "Squats", image: 'https://www.eatthis.com/wp-content/uploads/sites/4/2023/05/women-doing-squats.jpg?resize=800,586&quality=82&strip=all', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Squats sizning glutes, to'rtburchaklar va son mushaklaringizda ishlaydi, bu sizning metabolizmingizni kuchaytiradigan ozg'in mushaklarni qurishga yordam beradi, deb tushuntiradi Read.O'rnatish uchun oyoqlaringizni elkangiz kengligida erga qo'ying. Qo'llaringizni dumbangizga qo'ying, ularni ko'kragingiz bilan mahkamlang yoki qo'shimcha barqarorlik uchun ularni oldinga cho'zing. Ushbu mashqni kuchaytirish uchun siz yon tomonlaringizda dumbbelllar to'plamini ham ushlab turishingiz mumkin. Tizlaringizni egib, dumbalaringizni orqaga bosib cho'kishni boshlang. Sonlaringiz erga parallel yoki pastga tushguncha pastga tushiring. Tik turishga qaytish uchun ikkala oyog'ingizdan itaring. 12 dan 15 martagacha bo'lgan uchta to'plamni bajaring."]),
    Meal(name: "Pushups", image: 'https://www.eatthis.com/wp-content/uploads/sites/4/2023/06/woman-doing-pushups.jpg?resize=800,586&quality=82&strip=all', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Ularni seving yoki yomon ko'ring, push-uplar ajoyib kaloriya kuydiruvchisidir. Readga ko'ra, Pushups yuqori tanani va yadroni tonlash uchun juda yaxshi. Agar siz klassik push-uplarni juda qiyin deb hisoblasangiz, tizza yoki devorga surish bilan boshlang"]),
    Meal(name: "Lunges", image: 'https://www.eatthis.com/wp-content/uploads/sites/4/2023/04/woman-lunges-outdoors.jpg?resize=800,586&quality=82&strip=all', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["O'pka - bu pastki tanangizni, shu jumladan to'rtburchaklar, sonlar va glutalarni ishlaydigan yana bir samarali mashqdir.Boshlash uchun bir oyog'ingiz bilan oldinga katta qadam tashlang. O'pka harakatini boshlash uchun tizzalaringizni buking va pastga tushing. Yuqori tanangizni to'g'ri tuting va oldingi tizzangiz barmoqlaringizdan tashqariga chiqmasligiga ishonch hosil qiling. Keyin tik turish uchun oldingi tovoningizdan itaring. Orqa oyog'ingizni oldinga torting, boshqa tomondan o'tishni yakunlang. Har bir oyoq uchun 12 dan 15 gacha takroriy uchta to'plamni bajaring"]),
    Meal(name: "Mountain Climbers", image: 'https://www.eatthis.com/wp-content/uploads/sites/4/2023/05/woman-mountain-climbers.jpg?resize=800,586&quality=82&strip=all', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Alpinistlar bilan butun tanangizni ishlashga va yurak urish tezligini oshirishga tayyor bo'ling. Boshlash uchun, qo'llaringizni elkangizdan pastroq qilib, ikkala oyog'ingizni orqangizga cho'zgan holda baland taxtani oling. O'ng tizzangizni orqangizga cho'zishdan oldin tezda ko'kragingizga ko'taring. Keyin xuddi shu harakatni chap tizzangiz bilan takrorlang. 30 ta takrorlashdan iborat uchta to'plamni bajarayotganda muqobil qilishni davom eting."]),
    Meal(name: "Alternating Bird-Dogs", image: 'https://www.eatthis.com/wp-content/uploads/sites/4/2023/06/woman-bird-dogs.jpg?resize=800,586&quality=82&strip=all', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Va nihoyat, ayollar uchun kunlik vazn yo'qotish bo'yicha tavsiya etilgan mashqlar ro'yxati o'zgaruvchan qush-itlar bilan yakunlanadi. Boshlash uchun qo'llaringizni elkangiz bilan yuqoriga ko'tarib, tizzalaringizni soningizdan pastga qo'ying. O'ng qo'lingizni oldingizda va qarama-qarshi oyog'ingizni orqangizda tekislang. Bu holatda bir necha soniya turing. Keyin tizzangizni va tirsagingizni tanangiz ostida uchrashish uchun bir-biriga qarating. Qarama-qarshi tomondan takrorlang. 20 ta takrorlashning uchta to'plamini bajaring"]),
  ],
  [
    Meal(name: "Uxlash uchun eng yaxshi vaqt", image: 'https://avitsenna.uz/wp-content/uploads/2023/06/zdorovyj-son.jpg', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Toʻliq dam olish va tanani tiklash uchun kattalar kamida 8 soat uxlashlari kerak deb hisoblanadi. Uyqu — bu siklga ega jarayon boʻlib, unda har bir sikl tez va sekin uyquning oʻzgaruvchan bosqichlaridan iborat. Bitta siklning davomiyligi 1,5 soatni tashkil qiladi. Agar siz sikl oxirida uygʻonsangiz, unda uygʻonish oson boʻladi. Ammo siklning oʻrtasida uygʻongan boʻlsangiz, taxminan 6 soat uxlagan boʻlsangiz ham, uyqusizlik va charchoq hissi kun davomida qoladi."]),
    Meal(name: "Xurmoning inson organizmi uchun foydali xususiyatlari", image: 'https://cdn.trt.net.tr/images/xlarge/rectangle/5050/5223/8ad4/64bedbc6cd985.jpg?time=1692605161', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Xurmo — mazali va foydali meva. Xurmoda ham ko’pgina mevalarda bo’lgani kabi beta-karotin ko‘rinishidagi A vitamini bisyor. 100 gramm xurmodan organizm ushbu muhim elementlarning kunlik 12 foizini olish mumkin.A vitamini – kuchli antioksidant bo‘lib, hujayralarni erkin radikallardan himoya qiladi, qarish jarayonini sekinlashtirib, saraton rivojlanishi ehtimolini kamaytiradi. Turkiyada jannat mevasi yoki Trabzon xurmosi deb ataladigan ushbu meva yapon xurmosi yoki O'rta yer dengizi xurmosi kabi nomlar bilan ham ataladi."]),
    Meal(name: "Xotirani kuchaytirish uchun tabiiy vositalar", image: 'https://cdn.trt.net.tr/images/xlarge/rectangle/72ed/fd59/86e5/5a7d51934d27f.jpg?time=1692608619', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Xotira - bu markaziy asab tizimida sodir bo'lgan murakkab jarayon bo'lib, turli davrlarda olingan ma'lumotlarni idrok etish, to'plash, saqlash va ko'paytirishni o'z ichiga oladi."]),
    Meal(name: "Soyaning inson organizmi uchun foydalari", image: 'https://cdn.trt.net.tr/images/xlarge/rectangle/d0e8/e6da/b1f1/64b5462511894.jpg?time=1692608731', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Soya yuqori sifatli oqsildir. Kuniga bir yoki ikki porsiya soya mahsuloti sog'ligimiz uchun foydali bo'lishi mumkin. Soya suyak sog'lig'ini yaxshilaydi, shuningdek, yurak-qon tomir kasalliklari, insult va ba'zi saraton turlari kabi bir qator kasalliklar xavfini kamaytiradi."]),
  ],
  [
    Meal(name: "Sigareta chekish zarari va tamaki tutunining tanaga ta’siri", image: 'https://avitsenna.uz/wp-content/uploads/2021/03/kurenie-900x420-1.jpeg', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Sigareta tarkibidagi margimush — yurakdagi doimiy muammolarni keltirib chiqaradi. Saratonni qo’zg’atadigan va tanadan chiqarib yuborish juda qiyin bo’lgan zahar.Sigareta tarkibidagi formaldegid — zaharli kimyoviy birikma bo’lib, u birinchi navbatda nafas olish tizimiga ta’sir qiladi. Shunisi e’tiborga loyiqki, formaldegid patologlar tomonidan o’lik jasadlarni balzamlash uchun ishlatiladigan moddani — formalinni tayyorlash uchun ishlatiladi"]),
    Meal(name: "Chekishdan voz kechish umrni uzaytiradi", image: 'https://avitsenna.uz/wp-content/uploads/2017/02/chekishdan-vooz-kechish.jpg', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["AQSHning Merilendidagi saraton Milliy instituti mutaxassislari olti yil ichida 70 yoshdan katta bo‘lgan 160 ming kishini kuzatib bordi. Ular orasida doimiy chekuvchilar va chekishni tashlaganlar bo‘lgan. Tadqiqot ishtirokchilari orasida, uning yakuniga qadar vafot etganlar soni chekmaydiganlarda 12,1 foizni, chekuvchilarda esa 33,1 foizni tashkil qildi. Chekishni tashlaganlar orasida o‘lim xavfi ehtimoli 30 yoshdan undan voz kechganlarda 16,2 hamda 60 yoshidan tashlaganlarda 27,9 foizni tashkil etdi. Yoshlik paytida chekish 50 yoshdan kichik kishilarda yurak va qon-tomir kasalliklari xavfini 8 barobar oshiradi. Bu haqida Heart jurnalida chop etilgan maqolada ma’lum qilindi"]),
    Meal(name: "Me’yoridan ortiq suv ichish zararlari haqida bilasizmi?", image: 'https://cdn.xabardor.uz/media/photo/2022/05/05/news_photo-20220506-203044.webp', min: 0, price: 0, ingredients: ["(bu sahifada 'ingredients' ma'lumotlari mavjud emas!)"], steps: ["Tanadagi har qanday dardni davolash, vazn tashlashdan to kasallikka chalinmaslik uchun beriladigan eng universal tavsiya “suv iching” degan ibora bo‘lib qoldi. Lekin suv ichish doim har bizga foyda keltiradimi? Buyraklar soatiga taxminan 800-1000 ml.litr suvni qayta ishlashga qodir. Agar bu miqdor oshib ketadigan bo‘lsa, u holda tanadagi natriy balansi buziladi. Suv “mastlik” qon bosimini tartibga solishni qiyinlashtiradi, bu esa miya faoliyatiga, komaga va hatto o‘limga olib keladi. Bundan tashqari, shifokorlarning ta’kidlashicha, ortiqcha suv ichish suvsizlanish kabi xavfli. Ayniqsa buyrak bilan bog‘liq muammoga ega insonlar uchun"]),
  ],
];
